spring:
  application:
    name: IAScursos
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ep-dry-union-a8qce74w-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channelBinding=require}
    username: ${DATABASE_USERNAME:neondb_owner}
    password: ${DATABASE_PASSWORD:npg_46QRlWSZGpNE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

